### ISSUE TITLE
Potential alignment issue?

### ISSUE THREAD

**Issue by rlorigro** [ljdursi/poapy#6]
I have a new problem, but I am not entirely sure whether it is a bug or a "feature" inherent to POA. I am finding that the alignment strings of a POA graph do not retain the original order of the individual sequences that were fed to the graph.

e.g.:

```
Unaligned sequences:
ATATTGTGTAAGGCACAATTAACA
ATATTGCAAGGCACAATTCAACA
ATATTGCAAGGCACACAACA
ATGTGCAAGAGCACATAACA

Unaligned test sequence:
ATATTGCAAGGCACACTAACA

Aligned sequences:
0               ATATTGTGTAAG-GCACAATT--AACA
1               ATATTGC--AAG-GCACAATTC-AACA
2               ATATTGC--AAG-GCACA---C-AACA
3               ATGT-GC--AAGAGCACA---T-AACA
test            ATATTGC--AAG-GCACA---TCAACA
Consensus0      ATATTGC--AAG-GCACAATTC-AACA

Test before alignment
test     ATATTGCAAGGCACACTAACA
Test after alignment
test     ATATTGCAAGGCACATCAACA

```

I admit I haven't learned the details of POA yet, so this might just be a problem that comes with trying to linearly print a graph alignment. Here is the graph visualization, which shows that the out-of-order region is complex:

![poa_alignment_order_issue](https://user-images.githubusercontent.com/28764332/44236699-bb893b00-a162-11e8-9880-8816fa16e0ec.png)

And here is the code to reproduce this result:

```
from poapy import poagraph
from poapy import seqgraphalignment


def print_test_results(sequences, test_sequence, alignments):
    print("Unaligned sequences:")
    for sequence in sequences:
        print(sequence)

    print("\nUnaligned test sequence:")
    print(test_sequence)

    print("\nAligned sequences:")
    for read_id, alignstring in alignments:
        print("{0:15s} {1:s}".format(read_id, alignstring))

    print("\nTest before alignment")
    print("test\t", test_sequence)
    print("Test after alignment")
    print(alignments[-2][0], '\t', alignments[-2][1].replace("-",""))


def generate_poa_graph(sequences):
    """
    Initialize graph and align all sequences
    :param sequences:
    :return: graph: the completed POA graph resulting from the given sequences
    """
    init_sequence = sequences[0]
    init_label = "0"

    graph = poagraph.POAGraph(init_sequence, init_label)

    for i in range(1, len(sequences)):
        sequence = sequences[i]
        read_id = str(i)

        alignment = seqgraphalignment.SeqGraphAlignment(sequence, graph,
                                                        fastMethod=False,
                                                        globalAlign=True,
                                                        matchscore=1,
                                                        mismatchscore=-1,
                                                        gapscore=-2)

        graph.incorporateSeqAlignment(alignment, sequence, str(i))

    return graph


def test_order_of_alignment_minimal():
    sequences = ['ATATTGTGTAAGGCACAATTAACA',
                 'ATATTGCAAGGCACAATTCAACA',
                 'ATATTGCAAGGCACACAACA',
                 'ATGTGCAAGAGCACATAACA']
    test_sequence = "ATATTGCAAGGCACACTAACA"

    graph = generate_poa_graph(sequences)

    alignment = seqgraphalignment.SeqGraphAlignment(test_sequence, graph,
                                                    fastMethod=False,
                                                    globalAlign=True,
                                                    matchscore=1,
                                                    mismatchscore=-1,
                                                    gapscore=-2)

    graph.incorporateSeqAlignment(alignment, test_sequence, "test")

    alignments = graph.generateAlignmentStrings()

    print_test_results(sequences, test_sequence, alignments)

    with open("test_poapy.html", 'w') as file:
        graph.htmlOutput(file)

if __name__ == "__main__":
    test_order_of_alignment_minimal()
```

**Comment by ljdursi** [comment]
Hmm, this is a more subtle one, I'll take a look tomorrow

**Comment by rlorigro** [comment]
Hi, so I was able to massively simplify the test case. It appears that the problem comes from any case where the test sequence is longer than the sequences that initialized the graph. Here I have only 2 sequences of length 3, and a test sequence of length 4. It appears that this is another issue with the global alignment.

```
Unaligned sequences:
TTA
TGC

Unaligned test sequence:
TTGC

Aligned sequences:
0               TTA-
1               TGC-
test            TGCT
Consensus0      TGCT

Test before alignment
test     TTGC
Test after alignment
test     TGCT
```

But if we add arbitrary characters to the end of the sequence pool, the test no longer fails:

```
Unaligned sequences:
TTAA
TGCA

Unaligned test sequence:
TTGC

Aligned sequences:
0               TTAA
1               TGCA
test            TTGC
Consensus0      TTGC

Test before alignment
test     TTGC
Test after alignment
test     TTGC
```

Also, if we return to the failing case, and switch to local alignment, the test no longer fails:
```
Unaligned sequences:
TTA
TGC

Unaligned test sequence:
TTGC

Aligned sequences:
0               -TTA
1               -TGC
test            TTGC
Consensus0      TTGC

Test before alignment
test     TTGC
Test after alignment
test     TTGC
```

I haven't yet tested whether this is a result of the last bug fix. Would reverting to the previous version fix this? 

Here is the revised test script:
```
from poapy import poagraph
from poapy import seqgraphalignment


def generate_poa_graph(sequences):
    """
    Initialize graph and align all sequences
    :param sequences:
    :return: graph: the completed POA graph resulting from the given sequences
    """
    init_sequence = sequences[0]
    init_label = "0"

    graph = poagraph.POAGraph(init_sequence, init_label)

    for i in range(1, len(sequences)):
        sequence = sequences[i]
        label = str(i)

        alignment = seqgraphalignment.SeqGraphAlignment(sequence, graph,
                                                        fastMethod=False,
                                                        globalAlign=True,
                                                        matchscore=1,
                                                        mismatchscore=-1,
                                                        gapscore=-2)

        graph.incorporateSeqAlignment(alignment, sequence, label)

    return graph


def get_alignment_by_label(alignments, label):
    """
    iterate through poapy alignment tuples to find an alignment with the specified label
    :param alignments:
    :return:
    """
    query_alignment = None

    for alignment in alignments:
        if alignment[0] == label:
            query_alignment = alignment

    if query_alignment is None:
        exit("ERROR: query label not found in alignments")

    return query_alignment


def print_test_results(sequences, test_sequence, alignments):
    test_alignment = get_alignment_by_label(alignments, "test")

    print("Unaligned sequences:")
    for sequence in sequences:
        print(sequence)

    print("\nUnaligned test sequence:")
    print(test_sequence)

    print("\nAligned sequences:")
    for read_id, alignstring in alignments:
        print("{0:15s} {1:s}".format(read_id, alignstring))

    print("\nTest before alignment")
    print("test\t", test_sequence)
    print("Test after alignment")
    print(test_alignment[0], '\t', test_alignment[1].replace("-",""))


def test_order_of_alignment_minimal():
    sequences = ["TTA", "TGC"]
    test_sequence = "TTGC"

    graph = generate_poa_graph(sequences)

    alignment = seqgraphalignment.SeqGraphAlignment(test_sequence, graph,
                                                    fastMethod=False,
                                                    globalAlign=True,
                                                    matchscore=1,
                                                    mismatchscore=-1,
                                                    gapscore=-2)

    graph.incorporateSeqAlignment(alignment, test_sequence, "test")

    alignments = graph.generateAlignmentStrings()

    print_test_results(sequences, test_sequence, alignments)

    with open("test_poapy.html", 'w') as file:
        graph.htmlOutput(file)


if __name__ == "__main__":
    test_order_of_alignment_minimal()
```

**Comment by ljdursi** [comment]
Oh, nice find, I was looking in the wrong place entirely...

**Comment by ljdursi** [comment]
So this is unrelated to the earlier issue (although the earlier issue may have obscured this one).  In the last one, the bug was in the actual string-graph alignment, so resulted in an incorrect graph when added; here the graph is fine, the issue is "just" in the generation of the alignment strings for output.

Almost have it sorted...

**Comment by rlorigro** [comment]
Yea looking at the visualization, the correct sequence of nodes exists in the graph

**Comment by ljdursi** [comment]
So the key is here, where it's decided which column each node's character will be printed out in:

https://github.com/ljdursi/poapy/blob/master/poagraph.py#L394-L403

What caused the issue was that when a node is inserted an existing node that is aligned with an earlier node:

```
+-+   +-+   +-+
|T+--->T+--->G|
+++   +-+   +++
 |           |
 +--------->-++
            |T|
            +-+
```

The T/G alignment is assigned an earlier column than the inserted T, which is what you saw.  That case is relatively easily fixed by assigning the columns in reverse order, so aligned nodes are assigned the column of their _last_ occurring node:

```
        # go through nodes in reverse toposort order
        ni = self.nodeiterator()
        all_nodes = list(ni())
        for node in all_nodes[::-1]:
            other_columns = [column_index[other] for other in node.alignedTo if other in column_index]
            if len(other_columns) > 0:
                found_idx = min(other_columns)
            else:
                found_idx = current_column
                current_column += 1

            column_index[node.ID] = found_idx

        ncolumns = current_column

        # now reverse the columns back
        for node_id in column_index:
            column_index[node_id] = ncolumns - column_index[node_id] - 1
```

But then that causes problems with (say) examples/example1.fa; I'll need a bit more sophisticated approach to avoid the corner cases of this simple method...

**Comment by ljdursi** [comment]
Ok, so there's a solution that works for small cases in branch  `6_column_order`, with appropriate tests added; I've incorporated alignedTo edges in the topological sort, which is the fundamental issue being exposed by your very nice test cases.

This approach will almost always work, but by treating the alignedTo edges as normal edges, it runs the risk of creating cycles in the graph, which will cause the topological sort to fail.  So I'm going to leave this open a little while longer and not merge in the PR yet until I've implemented the more correct approach of merging the aligned-to nodes, doing the toposort, and then breaking the aligned-to nodes up again.

**Comment by rlorigro** [comment]
OK I see, it makes sense that the problem was related to the sorting method. Thanks (again) for your help with this.

I am going to try running the new branch on a genomic scale soon so I'll let you know if I find a new test case involving cycles :)

**Comment by rlorigro** [comment]
OK I found some new errors, but they seem to be of a different nature than expected. About 1 in 10 regions I tested have the same out-of-order issue as before the new branch:

if you use these sequences in the test script you should see the error:

case 1
```
    sequences = ["TAGTGAAAGAGGAAAAGAA"]
    test_sequence = "GCCCAGAAATTCCAGACCAGC"
```
case 2
```
    sequences = ["CTACTTGGGAGGCTGAGGTGG", "CCACTTGAGTTGAGG", "CTACTTGGGAAGCTAGAGGTGG"]
    test_sequence = "CTACTTGGGAGGCTGAGGTGG"
```
I tried trimming the sequences so that they are simpler, but any change I make seems to remove the problem.

Here is the output for case1:
```
Unaligned sequences:
TAGTGAAAGAGGAAAAGAA

Unaligned test sequence:
GCCCAGAAATTCCAGACCAGC

Aligned sequences:
0               TAGT-GAAAGAGGAAAAGA-A
test            GCCCAGAAATTCCAGACCACG
Consensus0      GCCCAGAAATTCCAGACCACG
Consensus1      TAGT-GAAAGAGGAAAAGA-A

Test before alignment
test     GCCCAGAAATTCCAGACCAGC
Test after alignment
test     GCCCAGAAATTCCAGACCACG
```

**Comment by rlorigro** [comment]
(accidentally toggled the issue closed/open just now, sorry)

So it seems like there is something more seriously wrong with the alignment itself, because I am getting very questionable pileups with poapy, where there is an offset in alignment

```
TCTTTATCCATTC
TCTTTGTCCATTTCATGCTTC
TCTTGTCCATTTCATGCTTC
TCTTTGTCCATTTCATGCTTC
TCTTGGTTCATTTCATGCTCG
TCTTGTCCATTTCATGTTTC
TCTTTGTCCATTTTCATACTTC
TCTTTGTCCATCATGCTTC
TCTTTGTCCATTTCATGCTTC
TCTTTGTCCATTTCATGCTTC
TCTTTGGTCCATTCTATGCTTCC
TTTCTTGTCCATTTCCATGCTTC
TCTTATCCATTTCATGCTTC
TCTGTCCATTTCATGCTTC
TCTTCCATTTCATGCTTC
TCTTTGTCCATTTCATGCTTC
TCTTTGTCCATTTCATGCTTC
TCCTTTATCCATTTCATGCTTCTC
TCTTTGTCCATTTCATGCTTC

0               TCTT--TATC-CATT-C-----------
1               TCTT--TGTC-CATTTC-A-TGCTTC--
2               TCTT--G-TC-CATTTC-A-TGCTTC--
3               TCTT--TGTC-CATTTC-A-TGCTTC--
4               TCTT--G-GTTCATTTC-A-TGCT-C-G
5               TCTT--G--TCCATTTC-A-TGTTTC--
6               TCTT--T-GTCCATTTTCA-TACTTC--
7               TCTT--T-GTCCAT--C-A-TGCTTC--
8               TCTT--T-GTCCATTTC-A-TGCTTC--
9               TCTT--T-GTCCATTTC-A-TGCTTC--
10              TCTT-TG-GTCCATTCT-A-TGCTTC-C
11              T-TTCTT-GTCCATTT-CCATGCT-T-C
12              TCTT---ATC-CATTT--CATGCT-T-C
13              TCTG---T-C-CATTT--CATGCT-T-C
14              TCTTCC------ATTT--CATGCT-T-C
15              TCTT-T--GTCCATTT--CATGCT-T-C
16              TCTT-T--GTCCATTT--CATGCT-T-C
17              TCCT-TT-ATCCATTT--CATGCTTCTC
18              TCTT-T--GTCCATTT--CATGCT-T-C
ref             TCTT-T--GTCCATTT--CATGCT-T-C
```
Following the insertion (?) of a C in sequence 11, every subsequent alignment is offset

**Comment by rlorigro** [comment]
I haven't check the graph viz to see if this is a printing error or a graph construction error.

**Comment by ljdursi** [comment]
Alright.  I've settled on a favourite way to do the topological sorting properly, and I'll get that implemented within the next day.  Once that's done, I'll merge it in, and we can determine if this is another more subtle manifestation of the same problem that doing things the hacky way didn't fix, or represents a different underlying issue.

**Comment by ljdursi** [comment]
Re the case of the C insertion in sequence 11, I think that's correct, or at least a faithful representation of what I'd expect the graph alignment to look like.  6 & 11 have a C inserted 2/3 of the way through the sequence (and 11 & 14 towards the beginning) relative to all the other sequences, so that's reflected in the alignment strings.

**Comment by ljdursi** [comment]
Ok, I've implemented a more thorough version of the same basic fix - merging alignedTo nodes for the purposes of the toposort - and I'm happy with how it's addressed the first four cases you've raised (all of which are now tests), although I think the need to do this suggests a design issue with the underlying graph representation I'm using.

**Comment by ekg** [comment]
It's great to have this implementation of POA in python! I'm hoping it will help a lot of people wrap their heads around POA and encourage the development of new algorithms in this space.

If you need an external point of reference, may I suggest looking at [vg](https://github.com/vgteam/vg). It includes `vg msga`, which can progressively build up a graph from a set of input sequences given in FASTA using a variant of partial order alignment.

In this particular example, if we rewrite it as a FASTA file, then we can run:

```
vg msga -f y.fa -k 1 -C 0 -L 20 >y.vg
vg index -x y.xg y.vg
vg viz -x y.xg -o y.svg
convert -density 1500 y.svg y.png
```

![y](https://user-images.githubusercontent.com/145425/44575086-7335d280-a78b-11e8-9d95-877a68167f44.png)

A `dot`-based rendering looks a bit confused but might also be helpful:

```
vg view -dp y.vg | dot -Tpng -o y.dot.png
```

![y dot](https://user-images.githubusercontent.com/145425/44575237-d6276980-a78b-11e8-87f8-a5768d08218f.png)

[y.fa.txt](https://github.com/ljdursi/poapy/files/2317696/y.fa.txt)

**Comment by ekg** [comment]
@ljdursi I'd be interested to know what functionality you'd like to see in python.

For the moment, you can at least talk with the methods in vg using line delimited JSON streams. See https://github.com/uio-bmi/pyvg for an example python wrapper.

Another point of interface could be the local alignment algorithms. There is GSSW (in C), https://github.com/vgteam/gssw. Another related algorithm is dozeu, which is X-drop DP but for graphs: https://github.com/ocxtal/dozeu.

**Comment by ekg** [comment]
>  "second opinion" on funny-looking alignments

Although here vg's alignments look just as funny!

**Comment by rlorigro** [comment]
Haha... funny you would mention vg, I hadn't thought about using their alignment, for some reason. I'll have to look more into their methods. I do like poapy because I can edit the source in Python. It serves as a educational template for a single algorithm.

So I think I poorly explained what I thought was "weird" about the alignments earlier. If you look back at the pileup:

```
0               TCTT--TATC-CATT-C-----------
1               TCTT--TGTC-CATTTC-A-TGCTTC--
2               TCTT--G-TC-CATTTC-A-TGCTTC--
3               TCTT--TGTC-CATTTC-A-TGCTTC--
4               TCTT--G-GTTCATTTC-A-TGCT-C-G
5               TCTT--G--TCCATTTC-A-TGTTTC--
6               TCTT--T-GTCCATTTTCA-TACTTC--
7               TCTT--T-GTCCAT--C-A-TGCTTC--
8               TCTT--T-GTCCATTTC-A-TGCTTC--
9               TCTT--T-GTCCATTTC-A-TGCTTC--
10              TCTT-TG-GTCCATTCT-A-TGCTTC-C
11              T-TTCTT-GTCCATTT-CCATGCT-T-C
12              TCTT---ATC-CATTT--CATGCT-T-C
13              TCTG---T-C-CATTT--CATGCT-T-C
14              TCTTCC------ATTT--CATGCT-T-C
15              TCTT-T--GTCCATTT--CATGCT-T-C
16              TCTT-T--GTCCATTT--CATGCT-T-C
17              TCCT-TT-ATCCATTT--CATGCTTCTC
18              TCTT-T--GTCCATTT--CATGCT-T-C
ref             TCTT-T--GTCCATTT--CATGCT-T-C
```

What I meant was that nearly every sequence after 11 has the substring "TTTCATGCTTC", but none of them align 1-to-1 with the sequences before 11. Looking more closely at two of the sequences, before and after 11 (or 10?) shows up:

```
8               TCTT--T-GTCCATTTC-A-TGCTTC--
18             TCTT-T--GTCCATTT--CATGCT-T-C
```

They actually are identical but have different alignments.

Which brings up another kind of test case. I'll load the updated branch in a couple hours and test it out.

**Comment by rlorigro** [comment]
at this point, maybe a new issue should be opened so we can close this one, but in case you want to spend some time on this rare exception, here is the test script. I combinatorially tested the above sequence set to find the minimal error case.

```
import poagraph
import seqgraphalignment


def get_alignments_by_sequence(alignments, sequence):
    query_alignments = list()

    for a, alignment in enumerate(alignments):
        current_sequence = alignment[1].replace("-",'')

        if current_sequence == sequence:
            query_alignments.append(alignment)

    if len(query_alignments) == 0:
        raise KeyError("ERROR: query sequence not found in alignments")

    return query_alignments


def generate_poa_graph(sequences, fastMethod=True, globalAlign=True, matchscore=1, mismatchscore=-1, gapscore=-2):
    """
    Initialize graph and align all sequences
    :param sequences:
    :return: graph: the completed POA graph resulting from the given sequences
    """
    init_sequence = sequences[0]
    init_label = "0"

    graph = poagraph.POAGraph(init_sequence, init_label)

    for i in range(1, len(sequences)):
        sequence = sequences[i]
        label = str(i)

        alignment = seqgraphalignment.SeqGraphAlignment(sequence, graph,
                                                        fastMethod=fastMethod,
                                                        globalAlign=globalAlign,
                                                        matchscore=matchscore,
                                                        mismatchscore=mismatchscore,
                                                        gapscore=gapscore)

        graph.incorporateSeqAlignment(alignment, sequence, label)

    return graph


def test_identical_sequence_subset(sequences, test_sequence, print_result=False):
    fastMethod = True
    globalAlign = True
    matchscore = 4
    mismatchscore = -4
    gapscore = -5

    graph = generate_poa_graph(sequences,
                               fastMethod=fastMethod,
                               globalAlign=globalAlign,
                               matchscore=matchscore,
                               mismatchscore=mismatchscore,
                               gapscore=gapscore)

    alignments = graph.generateAlignmentStrings()

    test_alignments = get_alignments_by_sequence(alignments=alignments, sequence=test_sequence)

    test_alignment_strings = [test_alignment[1] for test_alignment in test_alignments]

    alignment_string_set = set(test_alignment_strings)

    if print_result:
        print("\nPileup:")
        for read_id, alignstring in alignments:
            print("{0:15s} {1:s}".format(read_id, alignstring))

        print("\nAligned identical sequences:")
        for string in alignment_string_set:
            print(string)

    assert len(alignment_string_set) == 1


if __name__ == "__main__":
    sequences = ['TCTTTATCCATTC', 'TCTTGGTTCATTTCATGCTCG', 'TCTTTGTCCATTTCATGCTTC', 'TCTTTGTCCATTTCATGCTTC']

    test_sequence = "TCTTTGTCCATTTCATGCTTC"

    print("Minimum error set:")
    for sequence in sequences:
        print(sequence)

    test_identical_sequence_subset(sequences=sequences, test_sequence=test_sequence, print_result=True)
```

**Comment by rlorigro** [comment]
I also refactored all the other test cases and included this one in a single script: 
[test_all.py.txt](https://github.com/ljdursi/poapy/files/2319639/test_all.py.txt)

**Comment by rlorigro** [comment]
I know you're probably tired of these now but I found a case where this happens with the default parameters (match=1, mismatch=-1, gap=-2):

```
minimal error set:
('ACTGGACATTAGAA', 'ACTGGTATAGCCACGTTAGA', 'TCAGAGAAATACGGTGAA', 'ACTGGTATAGCCAATGCTAGAAA', 'ACTGGTATAGCCACGTTAGA')

Aligned sequences:
0               ACTG-G-A---C-A--T-TAGAA-
1               ACTG-GTATAGCCACGT-TAGA--
2               TCAGAG-AAAT--ACGG-T-GAA-
3               ACTG-GTATAGCCAATGCTAGAAA
4               ACTG-GTATAGCCACG--T-TAGA
Consensus0      ACTG-GTATAGCCACGGCTAGAAA

Identical sequences after alignment:
ACTG-GTATAGCCACGT-TAGA--
ACTG-GTATAGCCACG--T-TAGA

```

**Comment by ljdursi** [comment]
Hey, @rlorigro -

I think this could be usefully in another issue, since it's different from the problem of the first 4 cases.  I prefer to leave that to you as the issue-opener, though.

But this - at least the case immediately above - doesn't appear to be a bug to me; I think it reflects that you want a different scoring, or a different order of graph construction, than is being used to get the results you want.

Let's take a look at 1 + 4.  I'm running this using the following fasta file:

```
>0
ACTGGACATTAGAA
>1
ACTGGTATAGCCACGTTAGA
>2
TCAGAGAAATACGGTGAA
>3
ACTGGTATAGCCAATGCTAGAAA
>4
ACTGGTATAGCCACGTTAGA
```

Using the current code I get the following (re-ordered to put 1 & 4 beside each other for ease of comparison:

```
$ ./poa.py foo.fa --global
0               ACTG-G-A---C--A---TTA-GAA
2               TCAGAG-A---AATAC-GGT--GAA
3               ACTG-GTATAGCC-AATGCTAGAAA
Consensus0      ACTG-GTATAGCC-AC-GTTA-GAA
1               ACTG-GTATAGCC-AC-GTTA-GA-
4               ACTG-GTATAGCC-AC-GTTA--GA
```

It totally makes sense that you'd expect these two alignment strings to be the same.  Let's think about the score string 4 would get by aligning directly to string 1.  Obviously, there'd be 20 matches (+20), and the internal gaps wouldn't be penalized (because you're aligning to an existing path in the graph; those internal gaps in this case have basically already been opened).

However, with each alignment, you're aligning to the graph as a whole, not to to the previous strings, and we're doing a _global_ alignment here; so there's still a gap at the end of the global alignment which have to be scored, so there's a penalty of -2, for a total score of 18.

After sequence 2, there's a new path to the end of the graph and a new internal gap opened up (or a new path skipping over a base if you like) the alignment chosen for 4 now opens up no new gaps but replaces a match (+1) with a mismatch (-1) so just as optimal as the align-to-1 case.

If we do a local alignment, so that gaps at ends don't matter, we get something that's a bit more what you'd expect maybe:

```
$ ./poa.py foo.fa
0               ----------------------ACTGGAC-ATTA-GAA
2               TCAGAGAAAT-----------------AC-GGT--GAA
3               ----------ACTGGTATAGCC-----AATGCTAGAAA
Consensus0      ----------ACTGGTATAGCC-----AC-GTTAGAAA
Consensus1      TCAGAGAAAT-----------------AC-GGT--GAA
1               ----------ACTGGTATAGCC-----AC-GTTA-GA-
4               ----------ACTGGTATAGCC-----AC-GTTAGA--
```

But it's just as easy to switch to follow the end of sequence 3 as it is to follow the end of sequence 1.

It sounds like you'd like alignments to preferentially stick to one path to the graph, is that right?  There's a couple of ways to do this; one would be to have a change-path penalty, one would be to do some sort of pairwise progressive alignment (which would be a little tricky, right now there isn't a graph-to-graph alignment in the code base).  You may be able to find some scoring schemes in the literature which meet your needs, and we could talk about how to get those implemented here.

**Comment by rlorigro** [comment]
I see, so the issue is that the gap scores depend on whether a previous gap exists in the graph already, and certain reads have alignments that force gaps to be created. So POA is a greedy algorithm in that sense.

> It sounds like you'd like alignments to preferentially stick to one path to the graph, is that right? There's a couple of ways to do this; one would be to have a change-path penalty, one would be to do some sort of pairwise progressive alignment 

Well for my purposes, I am generating pileups, in which the reads are noisy but fairly confidently belong to the same underlying sequence. I just need their alignments to be consistent, and independent of the order of their alignment, because the ultimate goal is to use the alignment for consensus calling. Logically, I don't think a single read should change the fate of every subsequent read, especially in my use case, when I know that they all are noisy representations of the same sequence. Each individual read should be considered a minor contribution to the graph, which represents a sort of probability density of the true sequence.

Penalizing based on the weight of transitions seems like one way to implement your path-changing cost, but this is also order dependent. I think it has potential to solve this problem, where reads switch paths halfway through the pileup. But the density approach might also cause similar issues where the first several reads establish a seed that determines the fate of all the subsequent reads. 

I see why you mention pairwise progressive alignment, because a hierarchical approach would also help remove the order dependence. It would be less likely that this gap-introducing read causes half the reads to converge on an alternate alignment. If graphs could be independently generated and aligned in a sort of tournament bracket then the graph containing the deviant alignment could be phased out early.

One simple (hacky) solution would be to realign all the reads after the graph has been constructed. Also I am curious, given a choice of 2 equally scored paths, is the choice of alignment deterministic?

I'll close the issue, since all the bugs have been fixed.

**Comment by ljdursi** [comment]
I think it’s fair to open an issue on these sorts of scoring questions where we can discuss the options, even if the existing functionality isn’t technically broken, as discussion for a feature request.

I maybe shouldn’t have talked about “opening” the gap, but once a path exists in the graph it’s available to be followed, so if one sequence has bridged a gap and paid the gap penalty, there’s no additional alignment penalty for piling on that bridge...

I won’t have much opportunity to do any coding on this for the coming week, but I strongly suspect others have thought about this and can look into what’s been done in other graph approaches (as the msga approach in vg).

GIven two equally scored paths, the alignment choice is deterministic; the “choice” is made at each step depending simply on the order that the comparisons are done in calculating the max score.
